export const users = {
	status: 'success',
	data: {
		contactId: '3203527',
		agentNumber: '0101593',
		firstName: null,
		lastName: null,
		displayName: 'JAMES LEE',
		company: 'AELife',
		isToS: true,
		agentNumberHash: 'C165813800FA9C320331BA027011FAC6',
		canImpersonate: false,
		roles: ['Commissionable_Agent'],
		permissions: [
			'Attestation',
			'Book of Business',
			'Calculators',
			'Clients',
			'Dashboard - Agent View',
			'Opt in for Paperless',
			'Products',
			'ReadyApp',
			'Terms of Use - Commissions',
			'Terms of Use - Portal',
			'View Commission Schedule',
			'View Commission Statements',
		],
		isEAppEnabled: true,
		userType: 'Agent',
	},
};

export const Licenses = {
	status: 'success',
	data: [
		{
			id: '01',
			state: 'Florida',
			number: 'A209775',
			effectiveDate: '2017-09-14T00:00:00+00:00',
			expDate: null,
			status: 'Hold',
			reason: 'Holding Agent Appointment',
		},
		{
			id: '01',
			state: 'Georgia',
			number: '588442',
			effectiveDate: '2017-09-14T00:00:00+00:00',
			expDate: '2020-09-30T00:00:00+00:00',
			status: 'Terminated',
			reason: 'Terminated For Non-Production',
		},
		{
			id: '01',
			state: 'Illinois',
			number: '487698',
			effectiveDate: '2019-08-21T00:00:00+00:00',
			expDate: '2021-09-30T00:00:00+00:00',
			status: 'Terminated',
			reason: 'Terminated For Non-Production',
		},
		{
			id: '01',
			state: 'North Carolina',
			number: '487698',
			effectiveDate: '2023-04-26T00:00:00+00:00',
			expDate: null,
			status: 'Active',
			reason: 'Active Agent',
		},
		{
			id: '01',
			state: 'Oregon',
			number: '487698',
			effectiveDate: '2017-09-14T00:00:00+00:00',
			expDate: '2018-09-30T00:00:00+00:00',
			status: 'Terminated',
			reason: 'Terminated - License Canceled',
		},
		{
			id: '01',
			state: 'Tennessee',
			number: '836894',
			effectiveDate: '2023-04-12T00:00:00+00:00',
			expDate: '2025-09-30T00:00:00+00:00',
			status: 'Active',
			reason: 'Active Agent',
		},
		{
			id: '01',
			state: 'Texas',
			number: '1134478',
			effectiveDate: '2023-07-09T00:00:00+00:00',
			expDate: '2023-09-30T00:00:00+00:00',
			status: 'Active',
			reason: 'Active Agent',
		},
		{
			id: '01',
			state: 'Washington',
			number: '272609',
			effectiveDate: '2023-04-06T00:00:00+00:00',
			expDate: '2024-09-30T00:00:00+00:00',
			status: 'Active',
			reason: 'Active Agent',
		},
	],
};

export const RJ100ProfileInfo = {
	status: 'success',
	data: {
		nameFormat: 'Business',
		businessName: 'EDWARD P JONES & CO CUSTODIAN',
		firstName: null,
		lastName: null,
		primaryEmail: null,
		secondaryEmail: null,
		primaryPhone: '7275555360',
		secondaryPhone: null,
		preferredContactMethod: null,
		address: {
			street: '96 BOSSY DRIVE',
			city: 'WHAT CHEER',
			state: 'FL',
			zipCode: '33716',
			line2: null,
		},
		isPaperless: false,
		isPaperlessAnnualStatement: false,
		isPaperless11MonthSummary: false,
	},
};

export const NextNumber = {
	status: 'success',
	data: { delegateAgentNumber: 'EBD00098-24' },
};

export const Delegate = {
	status: 'success',
	data: {
		delegates: [
			{
				delegateAgentNumber: 'EBD00098-01',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Johnken',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: null,
				status: 'Active',
				createDateTime: '2024-03-18T05:24:07',
				modifiedDateTime: '2024-03-20T06:39:29',
			},
			{
				delegateAgentNumber: 'EBD00098-02',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Password Reset',
				createDateTime: '2024-03-18T05:29:42',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-03',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Password Reset',
				createDateTime: '2024-03-18T05:32:42',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-04',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John',
				lastName: 'William1',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Password Reset',
				createDateTime: '2024-03-18T05:36:06',
				modifiedDateTime: '2024-03-18T06:32:44',
			},
			{
				delegateAgentNumber: 'EBD00098-06',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-18T06:52:51',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-07',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-18T06:56:51',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-08',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John234',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-18T07:03:32',
				modifiedDateTime: '2024-03-20T06:16:35',
			},
			{
				delegateAgentNumber: 'EBD00098-09',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Johnn',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-18T07:08:07',
				modifiedDateTime: '2024-03-20T06:15:55',
			},
			{
				delegateAgentNumber: 'EBD00098-10',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'John',
				lastName: 'William',
				email: 'barath.lakshmanan@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-18T13:38:48',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-11',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Tomyykrish',
				lastName: 'Jerrykk',
				email: 'sivasivani.b@american-equity.com',
				permissions: null,
				status: 'Active',
				createDateTime: '2024-03-20T06:16:14',
				modifiedDateTime: '2024-03-20T06:35:28',
			},
			{
				delegateAgentNumber: 'EBD00098-12',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Krishh',
				lastName: 'K',
				email: 'krishnaveni.nadaraj@american-equity.com',
				permissions: null,
				status: 'Password Reset',
				createDateTime: '2024-03-20T06:17:12',
				modifiedDateTime: '2024-03-20T06:21:30',
			},
			{
				delegateAgentNumber: 'EBD00098-13',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Ashviga',
				lastName: 'Kannan',
				email: 'ashviga.arumugam@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Pending User Action',
				createDateTime: '2024-03-20T06:21:35',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-14',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Krishveni',
				lastName: 'sabari',
				email: 'krishnaveni.nadaraj@american-equity.com',
				permissions: null,
				status: 'Active',
				createDateTime: '2024-03-20T06:30:56',
				modifiedDateTime: '2024-03-20T06:38:14',
			},
			{
				delegateAgentNumber: 'EBD00098-15',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'Rapunzel',
				lastName: 'Eugene',
				email: 'sivasivani.b@american-equity.com',
				permissions: ['Commission Schedule'],
				status: 'Pending User Action',
				createDateTime: '2024-03-20T06:40:26',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-16',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'DP',
				lastName: 'DP',
				email: 'sivasivani.b@american-equity.com',
				permissions: null,
				status: 'Pending User Action',
				createDateTime: '2024-03-20T07:13:20',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-17',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'GTest',
				lastName: 'One',
				email: 'Gowrav.narendran@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Pending User Action',
				createDateTime: '2024-03-20T07:15:54',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-18',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'GTest',
				lastName: 'One',
				email: 'gowrav.narendran@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Pending User Action',
				createDateTime: '2024-03-20T10:42:37',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-19',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'GTest',
				lastName: 'Two',
				email: 'gowrav.narendran@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-20T10:43:59',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-20',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'GTest',
				lastName: 'Thress',
				email: 'gowrav.naredran@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Pending User Action',
				createDateTime: '2024-03-20T10:54:27',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-21',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'GTest',
				lastName: 'Four',
				email: 'gowrav.narendran@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Pending User Action',
				createDateTime: '2024-03-20T10:55:47',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-22',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'G',
				lastName: 'One',
				email: 'gowrav.narendran@american-equity.com',
				permissions: ['Commission Schedule', 'Commission Statements'],
				status: 'Active',
				createDateTime: '2024-03-20T10:56:44',
				modifiedDateTime: null,
			},
			{
				delegateAgentNumber: 'EBD00098-23',
				parentAgentContactId: '74701',
				parentAgentNumber: 'EBD00098',
				firstName: 'KokiDP3283',
				lastName: 'ADDDELEMAIL VALIDatn',
				email: 'kokila.chinnasamy@american-equity.com',
				permissions: null,
				status: 'Active',
				createDateTime: '2024-03-21T12:09:54',
				modifiedDateTime: '2024-03-22T09:55:50',
			},
		],
	},
};

export const Guidelines = {
	status: 'success',
	data: {
		description: [
			'American Equity does Just-in-Time appointments for producers in the following states and District of Columbia.',
			'Many states have guidelines as to how much time can pass between the date on an annuity application and the date an appointment is submitted to the state.',
			'Please be aware of these time constraints when submitting business in order to allow American Equity time to send your appointment to the state insurance department. If we are not able to send the appointment within the time specified by the state, we will have to ask you to get a new annuity application with a new sign date.',
		],
		timeframes: [
			{
				timeframe: '14 Days',
				states: 'California',
			},
			{
				timeframe: '15 Days',
				states: 'Alabama,  Arkansas,  Connecticut,  Delaware,  Georgia,  Hawaii,  Idaho,  Kentucky, Massachusetts,  Maine,  Michigan,  Minnesota,  Mississippi,  North  Carolina,  Nebraska,  Nevada,  New  Hampshire,  New  Jersey,  New  Mexico,  Oklahoma,  South  Carolina,  South  Dakota,  Tennessee,  Vermont,  Utah,  Washington, Wisconsin, West Virginia, Wyoming',
			},
			{
				timeframe: '30 Days',
				states: 'Iowa, Kansas, North Dakota, Ohio, Texas, Virginia, District of Columbia',
			},
			{
				timeframe: '45 Days',
				states: 'Florida',
			},
		],
		limitations: [
			{
				title: 'The following states do not allow us to pay commissions until the department of Insurance has confirmed the appointment:',
				content: [
					'Alabama, Hawaii, Kentucky, Michigan, North Carolina, South Dakota',
				],
			},
			{
				title: 'There are no appointments in these states:',
				content: [
					'Alabama, Hawaii, Kentucky, Michigan, North Carolina, South Dakota',
				],
			},
			{
				title: 'Pre-appointment states:',
				content: [
					'Louisiana and Montana - Can backdate business 15 days from contract date',
					'Pennsylvania and Utah - No backdating',
				],
			},
		],
	},
};
